#!/bin/bash

# POSX Production Database Setup Guide

echo "Setting up POSX Production Database..."
echo ""
echo "Step 1: Add DATABASE_URL to Vercel"
echo "----------------------------------------"
echo "Go to: https://vercel.com/roberts-projects-12ebd1a5/posx/settings/environment-variables"
echo ""
echo "Add a new environment variable:"
echo "  Name: DATABASE_URL"
echo "  Value: (copy POSTGRES_PRISMA_URL from below)"
echo ""
echo "POSTGRES_PRISMA_URL value:"
cat .env.production.local | grep POSTGRES_PRISMA_URL | cut -d'=' -f2- | tr -d '"'
echo ""
echo ""
echo "Step 2: Redeploy your application"
echo "----------------------------------------"
echo "Go to: https://vercel.com/roberts-projects-12ebd1a5/posx"
echo "Click 'Redeploy' on the latest deployment"
echo ""
echo ""
echo "Step 3: Push database schema"
echo "----------------------------------------"
echo "After redeploy completes, run:"
echo "  npx prisma db push"
echo ""
echo ""
echo "Step 4: Seed the database (optional)"
echo "----------------------------------------"
echo "To add sample data, run:"
echo "  npx prisma db seed"
echo ""
